services:
  backend:
    image: baboonmd-backend:dev
    build:
      context: backend
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - FRONTEND_CORS_URL=http://localhost:5173
      - FRONTEND_EDITOR_URL=http://frontend:5173/editor

  frontend:
    image: baboonmd-frontend:dev
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend