services:
  backend:
    image: baboonmd-backend:dev
    build:
      context: backend
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    image: baboonmd-frontend:dev
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend