FROM node:24-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

RUN apt-get update && \
    apt-get install -y --no-install-recommends chromium && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    libnss3 libxss1 libatk-bridge2.0-0 libgtk-3-0 libx11-xcb1 \
    libasound2 fonts-liberation libxcomposite1 libxdamage1 libgbm1 \
    libxrandr2 libpango-1.0-0 libcups2 libdrm2 libatk1.0-0 libatspi2.0-0 \
 && rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
ENV NODE_ENV=production
ENV PORT=8000

COPY . .

EXPOSE 8000

CMD ["node", "server.js"]
